name = "glixir"
version = "0.2.1"
description = "Easy interop library for Gleam-> oElixir OTP"

licences = ["MIT"]
repository = { type = "github", user = "rjpruitt16", repo = "genserver" }
#links = [
#  { title = "Sponsor", href = "https://github.com/sponsors/your-username" },
#  { title = "Examples", href = "https://github.com/your-username/gleam-elixir-interop-example" },
#]

gleam = ">= 1.7.0"
#For a full reference of all the available options, you can have a look at
# https://glieam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_erlang = ">= 0.34.0 and < 2.0.0"

gleeunit = ">= 1.0.0 and < 2.0.0"
logging = ">= 1.3.0 and < 2.0.0"
