name = "glixir"
version = "1.3.1"
description = "A safe(ish) interop library for Gleam to use Elixir's OTP"

licences = ["MIT"]
repository = { type = "github", user = "rjpruitt16", repo = "genserver" }
#links = [
#  { title = "Sponsor", href = "https://github.com/sponsors/your-username" },
#  { title = "Examples", href = "https://github.com/your-username/gleam-elixir-interop-example" },
#]

gleam = ">= 1.7.0"
#For a full reference of all the available options, you can have a look at
# https://glieam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_erlang = ">= 0.34.0 and < 2.0.0"

gleeunit = ">= 1.0.0 and < 2.0.0"
logging = ">= 1.3.0 and < 2.0.0"
phoenix_pubsub = ">= 2.1.3 and < 3.0.0"
envoy = ">= 1.0.2 and < 2.0.0"
gleam_json = ">= 3.0.2 and < 4.0.0"
syn = ">= 3.3.0 and < 4.0.0"
libcluster = ">= 3.5.0 and < 4.0.0"
